os:
  - linux
  - osx

language: node_js
node_js:
  - "4.0.0"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - curl https://install.meteor.com | /bin/sh
  - node --version
  - meteor --version

script:
  - node make.js test.cover.send