os:
  - linux
  - osx

sudo: required
language: node_js
node_js:
  - "6"

env:
  global:
    - CXX=g++-4.8
    - ELECTRIFY_TESTS_DEFAULT_STOP_TIMEOUT=60000

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - curl https://install.meteor.com | /bin/sh
  - meteor --version

script:
  - node make.js test.cover.send